name: Launch Release

on:
  push:
    branches:
      - publish

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # --- SETUP ---
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Get package info
        id: package_info
        run: |
          echo "version=$(bun run -e 'console.log(require("./package.json").version)')" >> $GITHUB_OUTPUT
          echo "name=$(bun run -e 'console.log(require("./package.json").name)')" >> $GITHUB_OUTPUT

      # --- SOURCE ZIP ---
      - name: Prepare source code zip
        uses: vimtor/action-zip@v1.2
        with:
          files: ./
          dest: releases/${{ steps.package_info.outputs.name }}_${{ steps.package_info.outputs.version }}_source.zip

      # --- BUILD ---
      - name: Install dependencies
        run: bun install

      - name: Build extension
        run: bun run prod

      # --- TAG ---
      - name: Create Tag
        run: git tag v${{ steps.package_info.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Tag
        run: git push origin v${{ steps.package_info.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- CHANGELOG ---
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n**Full Changelog:** #{{RELEASE_DIFF}}",
              "pr_template": "- #{{TITLE}} by @#{{AUTHOR}} in ##{{NUMBER}}",
              "categories": [
                {
                  "title": "## What's Changed"
                }
              ]
            }

      # --- RELEASE ---
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package_info.outputs.version }}
          release_name: ‚è© v${{ steps.package_info.outputs.version }}
          body: ${{ steps.github_release.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Chrome
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releases/${{ steps.package_info.outputs.name }}_${{ steps.package_info.outputs.version }}_chrome.zip
          asset_name: ${{ steps.package_info.outputs.name }}_${{ steps.package_info.outputs.version }}_chrome.zip
          asset_content_type: application/zip

      - name: Upload Release Asset Firefox
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releases/${{ steps.package_info.outputs.name }}_${{ steps.package_info.outputs.version }}_firefox.zip
          asset_name: ${{ steps.package_info.outputs.name }}_${{ steps.package_info.outputs.version }}_firefox.zip
          asset_content_type: application/zip

      # --- DISCUSSION ---
      - name: Create a new GitHub Discussion
        uses: abirismyname/create-discussion@v1.2.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "ü§ñ Hey, it's an update: Save My Chatbot v${{ steps.package_info.outputs.version }}"
          body: ${{ steps.github_release.outputs.changelog }}
          repository-id: ${{ secrets.repository_id }}
          category-id: ${{ secrets.category_id }}

      # --- PUBLISH ---
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3.7.0
        with:
          keys: ${{ secrets.BPP_KEYS }}
          chrome-file: releases/${{ steps.package_info.outputs.name }}_${{ steps.package_info.outputs.version }}_chrome.zip
          firefox-file: releases/${{ steps.package_info.outputs.name }}_${{ steps.package_info.outputs.version }}_firefox.zip
          edge-file: releases/${{ steps.package_info.outputs.name }}_${{ steps.package_info.outputs.version }}_chrome.zip
          source: releases/${{ steps.package_info.outputs.name }}_${{ steps.package_info.outputs.version }}_source.zip
          notes: "1. Go to Phind.com or Perplexity.ai, then start a new search.\n2. Click on the extension icon to download a formatted markdown file containing the conversation."

      # --- CLEANUP ---
      - name: Delete the 'publish' branch
        if: github.ref == 'refs/heads/publish'
        run: |
          git push origin --delete publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}